### ISSUE TITLE
no node.js

### ISSUE THREAD

**Issue by tofr** [kkysen/TexDBook#1]

**Comment by tofr** [comment]
Confirmation of receipt of this message requested. node.js is a no-go...

**Comment by kkysen** [comment]
We are only using Node for Webpack for compiling all our JavaScript and Typescript files into a single bundle file run in the browser.  We're not using Node at all to run any of our code for a server or anything else.  We're only using Python for the backend and Node only for compiling JavaScript for the frontend.  I did the same thing for my last project and you said it was okay so I thought it would be fine for the final project, too. Is it not?

**Comment by tofr** [comment]
Aaah yes. That sounds ok.

Seems I did not look closely enough.

Topher Brown Mykolyk
CS - Stuyvesant
+

**Comment by kkysen** [comment]
Approved
