### ISSUE TITLE
.conf file missing

### ISSUE THREAD

**Issue by tofr** [kkysen/TexDBook#3]
CREATE THE CORRECT GITHUB DIRECTORY STRUCTURE -- Done By Group
-------------------------
Your github repo should look like this:
<appname>.wsgi
<appname>.conf
README.md
docs/
	<put all documents not required by your app here (devlog, design doc etc)>
<appname>/
	__init__.py
	<put all app files and directories here>

https://docs.google.com/document/d/e/2PACX-1vTQ8PEz3yUZ5G85bbEvoZe_BlmP4fcH8Y-HBdrE7T_ZDQPPARXmTWJi08mIF74NWDr-ysWxa6mFofF-/pub

**Comment by kkysen** [comment]
It's generated by the Makefile when the install script is run, but I added the generated TexDBook.conf file there anyways.
