### ISSUE TITLE
more transparency required

### ISSUE THREAD

**Issue by tofr** [kkysen/TexDBook#4]
readme must document clearly what your scripts will try to install.

**Comment by kkysen** [comment]
I explained what the install script does in the README.

This is what it does:
  - installs the necessary dependencies,
  - clones or pulls this repo into `/var/www/TexDBook`,
  - runs `make install`, which installs more dependencies and sets up some data files,
  - generates the conf file `TexDBook.conf` and copies it to `/etc/apache2/sites-available/`,
  - enables the site with `a2ensite`,
  - and reloads Apache with `service apache2 reload`.
